name: alphafold 
channels:
  - nvidia
  - pytorch  # Add the PyTorch channel
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch
  - torchvision
  - matplotlib
  - ipykernel
  - modelcif
  - pip 
  - ffmpeg
  - py3dmol
  - nbformat