name: alphafold 
channels:
  - nvidia
  - pytorch  # Add the PyTorch channel
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - matplotlib
  - cpuonly
  - ipykernel
  - ipywidgets
  - ipympl
  - pip 

